spam = 'Hellow world!'

# print(spam.upper())
# print(spam.lower())
# print(spam.islower())
# print(spam.isupper())
# print(spam.isalpha())
# print(spam.isalnum())
# print(spam.isdecimal())
# print(spam.isspace())
# print(spam.istitle())
# print(spam.startswith('Hello'))
# print(spam.endswith('world!'))
# print(','.join(['cats','rats','bats']))
# print('My name is Simon'.split())
# print('Hello'.rjust(10))
# print('Hello'.ljust(10, '*'))
# print('Hello'.center(20, '='))
# print('    hello'.strip())
# print('   hello   '.lstrip())
# print('   hello   '.rstrip())
# print(spam.replace('e', 'xyz'))
